# fly.toml app configuration file generated for acfirst-strapi on 2023-07-18T17:13:23+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "acfirst-strapi"
primary_region = "sin"

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source="uploads"
  destination="/opt/app/public/uploads"
