services:
  - type: web
    name: acfirst-strapi
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    repo: https://github.com/lyeyixian/acfirst-strapi
    branch: main
    healthCheckPath: /_health
    autoDeploy: false
    disk:
      name: strapi-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 16.14.2
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: strapi-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true

databases:
  - name: strapi-postgres
    plan: free
