services:
  - type: web
    name: acfirst-strapi
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    repo: https://github.com/lyeyixian/acfirst-strapi
    branch: main
    healthCheckPath: /_health
    autoDeploy: false
    region: singapore
    envVars:
      - key: NODE_VERSION
        value: 16.14.2
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true

  - type: web
    name: acfirst-web
    env: node
    plan: free
    repo: https://github.com/lyeyixian/acfirst-web
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: STRAPI_URL_BASE
        fromService:
          type: web
          name: acfirst-strapi
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: strapi-postgres
    plan: free
    region: singapore
